"""empty message

Revision ID: ae51bf348114
Revises: d4156c9e3934
Create Date: 2025-06-08 04:12:18.088214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae51bf348114'
down_revision = 'd4156c9e3934'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=50), nullable=False))
        batch_op.drop_column('lastname')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lastname', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_column('name')

    # ### end Alembic commands ###
